PWC_DASHBOARD/PWC_DASHBOARD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/', include('project.urls')),
    path('manager/', include('manager.urls')),
    path('', include('dashboard.urls')),
]

PWC_DASHBOARD/manager/urls.py
from django import views
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.ManagerListView.as_view(), name="manager-list"),
    path('managercreate/', views.ManagerCreateView.as_view(), name="manager-create"),
    path('managerdetail/<str:pk>',
         views.Managerdetail, name="manager-detail"),

    #     path('managerdetail/<str:pk>',
    #          views.ManagerDetailView.as_view(), name="manager-detail"),
    #     path('managerupdate/<str:pk>',
    #          views.ManagerUpdateView.as_view(), name="manager-update"),
    path('managerdelete/<str:pk>',
         views.ManagerDeleteView.as_view(), name="manager-delete"),
    path('update_user/', views.Update_profile, name='update_user'),
]

PWC_DASHBOARD/project/models.py
from operator import mod
from pyexpat import model
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_manager = models.BooleanField(default=False)
    name = models.CharField(max_length=100, null=True)
    email = models.EmailField(unique=True)
    designation = models.CharField(max_length=150, null=True)
    username = models.CharField(max_length=100, null=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Manager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organistation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.email


class Status(models.Model):
    # imformation,test,dev,pwd,aws,.....
    name = models.CharField(max_length=50)
    # organistation=models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


def get_status():
    return Status.objects.get(name="Green")


TYPE_CHOICES = (
    ("Erp", "Erp"),
    ("aws", "aws"),
    ("Azure", "Azure"),
    ("salesforce", "salesforce"),
    ("5", "5"),
    ("6", "6"),
    ("7", "7"),
    ("8", "8"),
)


class Project(models.Model):

    title = models.CharField(max_length=200, null=False, blank=True)
    description = models.TextField(null=False, blank=True)
    client = models.CharField(max_length=50, null=False, blank=True)
    from_duration = models.DateField(null=True, blank=True)
    to_duration = models.DateField(null=True, blank=True)
    type = models.CharField(
        max_length=20,
        choices=TYPE_CHOICES,
        null=True
    )
    # phase = models.CharField(max_length=50, null=False, blank=True)
    # source=models.CharField(choices=SOURCE_CHOICE,max_length=100)
    organistation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    manager = models.ForeignKey(Manager, on_delete=models.CASCADE)
    status = models.ForeignKey(
        "Status", related_name="projects", on_delete=models.SET_NULL, null=True, blank=True, default=get_status)
    test = models.CharField(max_length=100, null=True,
                            blank=True, default="Green")
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)

    def __str__(self):
        return self.title
# employee


class Associates(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    manager = models.ForeignKey(Manager, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=False, blank=True)
    email = models.EmailField(null=True, blank=True)
    designation = models.CharField(max_length=100, null=False, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)

    def __str__(self):
        return self.name
# phase


class Phase(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Technology(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Associate(models.Model):

    name = models.CharField(max_length=200, null=False, blank=True)
    email = models.EmailField(null=True, blank=True)
    designation = models.CharField(max_length=100, null=False, blank=True)
    joindate = models.DateField(null=True)
    occupency = models.IntegerField(null=True, blank=True, default=0)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)
    technology = models.ManyToManyField(Technology)

    def __str__(self):
        return self.name


class Project_Associate(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    associate = models.ForeignKey(Associate, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)

    def __str__(self):
        return self.project.title + ":" + self.associate.name


class Technoproject(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    manager = models.ForeignKey(Manager, on_delete=models.CASCADE)
    associates = models.ForeignKey(Associates, on_delete=models.CASCADE)
    technology = models.ForeignKey(Technology, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)

    def __str__(self):
        return self.project.title + ":" + self.associates.name + ":" + self.technology.name


class PhaseDurationOfProject(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    phase = models.ForeignKey(Phase, on_delete=models.CASCADE)
    from_date = models.DateField(null=True, blank=True)
    to_date = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)
    # organistation=models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return (self.project.title)+" -- "+self.phase.name+" -- " + str(self.from_date)+" -- "+str(self.to_date)

PWC_DASHBOARD/project/forms.py
from turtle import color
from django.forms import DateInput, TextInput
from dataclasses import field
from django.forms import ModelForm
from .models import*
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .widget import DatePickerInput
User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']
        # field_classes = {'username': UsernameField}


class ProjectUpdateforms(ModelForm):
    class Meta:
        model = Project
        fields = ('title', 'client', 'description',
                  'from_duration', 'to_duration', 'status', 'type')

        widgets = {
            'from_duration': DatePickerInput(),
            'to_duration': DatePickerInput(),
        }


class Projectforms(ModelForm):
    class Meta:
        model = Project
        fields = ('type',)

#         widgets = {
#             'from_duration': DatePickerInput(),
#             'to_duration': DatePickerInput(),
#         }


class ProjectStatusUpdateForm(ModelForm):
    class Meta:
        model = Project
        fields = ("status",)


# class ProjectPhaseUpdateForm(ModelForm):
#     class Meta:
#         model = Project
#         fields = ("phase",)


class TechnologyForm(forms.Form):
    technology = forms.CharField(max_length=255, required=True)


class PhaseDurationForm(ModelForm):
    class Meta:
        model = PhaseDurationOfProject
        fields = ('phase', 'from_date', 'to_date')
        widgets = {
            'from_date': DatePickerInput(),
            'to_date': DatePickerInput(),
        }


class Associatesforms(ModelForm):
    class Meta:
        model = Associate
        fields = ("name", "email", "designation", "technology",)


class AssignAssociatesforms(ModelForm):
    class Meta:
        model = Project_Associate
        fields = ('associate',)


class CreateAssociatesForm(ModelForm):

    class Meta:
        model = Associate
        fields = ['name', 'email', 'designation', 'joindate', 'technology']
        widgets = {
            'joindate': DatePickerInput(),
        }

PWC_DASHBOARD/templates/associates/associates_create.html
{% extends "layouts/base.html" %} {% block title %} Project Update {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  
<style>
   html, body {
   min-height: 100%;
   }
  
   h1 {
   position: absolute;
   margin: 0;
   font-size: 40px;
   color: #fff;
   z-index: 2;
line-height: 83px;
   }
   textarea {
   width: calc(100% - 12px);
   padding: 5px;
   }
   .testbox {
   display: flex;
   justify-content: center;
   align-items: center;
   height: inherit;
   padding: 20px;
   }
   form {
   width: 100%;
   padding: 20px;
   border-radius: 6px;
   background: #fff;
   box-shadow: 0 0 8px #95b3eb; 
   }
   .banner {
   position: relative;
   height: 300px;
   background-image: url("/uploads/media/default/0001/02/e2502bb5e1dab7d5cc9b011c745033821aad632c.jpeg");  
   background-size: cover;
   display: flex;
   justify-content: center;
   align-items: center;
   text-align: center;
   }
   .banner::after {
   content: "";
   background-color: rgba(0, 0, 0, 0.2); 
   position: absolute;
   width: 100%;
   height: 100%;
   }
   input, select, textarea {
   margin-bottom: 10px;
   border: 1px solid rgb(83, 49, 49);
   border-radius: 3px;
   }
   input {
   width: calc(100% - 10px);
   padding: 5px;
   }
   
  
   .item:hover p, .item:hover i, .question:hover p, .question label:hover, input:hover::placeholder {
   color:  #006622;
   }
   .item input:hover, .item select:hover, .item textarea:hover {
   border: 1px solid transparent;
   box-shadow: 0 0 3px 0  #006622;
   color: #006622;
   }
   .item {
   position: relative;
   margin: 10px 0;
   }
   .item span {
   color: red;
   }
<<<<<<< HEAD
  
=======
   {% comment %} input[type="date"]::-webkit-inner-spin-button {
   display: none;
   }
>>>>>>> 31a8122220e9b20f86ed84f8ce52b0b676181f2d
   .item i, input[type="date"]::-webkit-calendar-picker-indicator {
   position: absolute;
   font-size: 20px;
   color: #00b33c;
   } {% endcomment %}
   .item i {
   right: 1%;
   top: 30px;
   z-index: 1;
   }
.week {
   display:flex;
   justify-content: space-between ;
  
   }
   .colums {
   display:flex;
   justify-content:space-between;
   flex-direction:row;
   flex-wrap:wrap;
   }
   .colums div {
   width:48%;
   }
   [type="date"]::-webkit-calendar-picker-indicator {
   right: 1%;
   z-index: 2;
   opacity: 0;
   cursor: pointer;
   color: red;
   }
   input[type=radio], input[type=checkbox]  {
   display: none;
   }
   label.radio {
   position: relative;
display: inline-block;
   margin: 5px 20px 15px 0;
   cursor: pointer;
   }
   .question span {
   margin-left: 30px;
   }
   .question-answer label {
   display: block;
   }
  
  
   .flax {
   display:flex;
   justify-content:space-around;
   }
   .btn-block {
   margin-top: 10px;
   text-align: center;
   }
  
  
   @media (min-width: 568px) {
   .name-item, .city-item {
   display: flex;
   flex-wrap: wrap;
   justify-content: space-between;
   }
   .name-item input, .name-item div {
   width: calc(50% - 20px);
   }
   .name-item div input {
   width:97%;}
   .name-item div label {
   display:block;
   padding-bottom:5px;
   }
   .container{
          margin-top: 60px;
      }
   }

  
   #id_type{
      border-color:#1de9b6;
      height: 30px;
      width: 100px;
   }
  

    #id_technology{
        height: 100px;
        width: 200px;
       
    
   }
      
  

   
 </style>
 {%endblock stylesheets%}
{% block content %}
 

   
     
<div class="container">
   <div class="page-header">
   <div class="page-block">
     <div class="row align-items-center">
       <div class="col-md-12">
         <div class="page-header-title">
           <h5 class="m-b-10"> Add Associates</h5>
         </div>
         <ul class="breadcrumb">
           <li class="breadcrumb-item">
             <a href="/"><i class="feather icon-home"></i></a>
           </li>
           
           <li class="breadcrumb-item">
             <a href="javascript:">  Associates </a>
           </li>
         </ul>
       </div>
     </div>
   </div>
 </div>
          <legend>Add New Associates</span></legend>
          <form method="POST">
            {% csrf_token%}
           <div class="colums">
          <div class="item">
            <label for="fname"> Name</label>
            {{form.name}}
          </div>
          <div class="item">
            <label for="email"> Email</label>
            {{form.email}}
          </div>
 <div class="item">
            <label for="designation">Designation</label>
            {{form.designation}}
          </div>
  <div class="item">
            <label class="date" >Join date</label>
            {{form.joindate}}
          </div>
          <div class="item">
            <label for="date">Technology</label>
            <br>
            {{form.technology}}
          </div>
  
 
            
                     
                         
          </div>
                </fieldset>
        <div class="btn-block">
          <button class="btn btn-dark" type="submit" >Submit</button>
        </div>
      </form>
    </div>



   </div>

{% endblock content %}

PWC_DASHBOARD/templates/associates/associates_data.html
{% extends "layouts/base.html" %} {% block title %} Associates {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} 
 {% block content %}
<style>
  .container {
    margin-top: 60px;
  }
</style>
<div class="container">
<div class="page-header">
  <div class="page-block">
    <div class="row align-items-center">
      <div class="col-md-12">
        <div class="page-header-title">
          <h5 class="m-b-10">Associates List</h5>
        </div>
        <ul class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/"><i class="feather icon-home"></i></a>
          </li>
        
          <li class="breadcrumb-item">
            <a href="javascript:">Associates</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

  <div class="row">
    <div class="col-md-9 ">
 
    </div>
    <div class="col-md-3 ">
  {% if request.user.is_manager %}
  <a  class="label theme-bg2 text-white f-12" href="{% url  'create_associates' project.id%}"
    >
      Add Associate
    </a
  >
  {%endif%}
  </div>
</div>
  <hr />
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Designation</th>
          <th scope="col">Technology</th>
          {% if request.user.is_manager %}
          <th>Action</th>
          {%endif%}
        </tr>
      </thead>
      <tbody>
        {% for i in e %}
        <tr>
          <td>{{i.name}}</td>
          <td>{{i.email}}</td>
          <td>{{i.designation}}</td>
          <td><a
            href="{% url 'get_technology' i.id%}"
            class="label theme-bg2 text-white f-12"
            >view</a
          ></td>
          {% if request.user.is_manager %}
        <td >
          <a
          href="{% url 'update_associates' i.id%}"
          class="label theme-bg2 text-white f-12"
          >Update</a
        ><a
          href="{% url 'associates-delete' i.id %}"
          class="label theme-bg text-white f-12"
          >Delete</a
        >
         
        </td>
        {%endif%}
      </tr>
        {% endfor%}
      </tbody>
    </table>
  </div>
  {% endblock content %}



  {% block javascripts %}{% endblock javascripts %}

PWC_DASHBOARD/templates/associates/associates_detail.html
{% extends "layouts/base.html" %} {% block title %} Project Detail {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} 
{% block content %}
<style>
    .container {
      margin-top: 10px;
    }
  </style>
  <div class="container">
    <ul class="list-group" style="color: #182443">
      <li
        class="list-group-item active"
        style="border-color: #4fc98d; background-color:#3f4d67"
      >
        This is the detail of <b>{{associate.name}}</b>
      </li>
  
      <li class="list-group-item">Email: {{associate.email}}</li>
      <li class="list-group-item">Join Date : {{associate.joindate}}</li>
      <li class="list-group-item">
        Designation: {{associate.designation}}
      </li>
      <li class="list-group-item">
       Created Date: {{associate.created}}
      </li>
     
      <li class="list-group-item">
      Associates Technology :
        <table class="table table-bordered" style="color: #b52e2e">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Technology</th>
              
            </tr>
          </thead>
          <tbody>
            {% for j in associate.technology.all %}
            <tr>
              <th scope="col">{{ forloop.counter }}</th>
              <th scope="col">{{ j.name }}</th>
              
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </li>
       <li class="list-group-item"> 
       Assigned Project: {{associate.occupency}}
        <table class="table table-bordered" style="color: #b52e2e">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Assigned Date</th>
              <th scope="col">Project</th>
              <th scope="col">Client</th>
              <th scope="col">Manager</th>
             
              
            </tr>
          </thead>
          <tbody>
            {% for i in a%}
            <tr>
              <th scope="col">{{ forloop.counter }}</th>
              <th scope="col">{{ i.created|date:" d M Y" }}</th>
              <th scope="col">{{i.project.title}}</th>
              <th scope="col">{{i.project.client}}</th>
              <th scope="col">{{i.project.manager.user.name}}</th> 
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </li> 
      <!-- <li class="list-group-item">Manager: {{project.manager}}</li>
      <li class="list-group-item">Organisation: {{project.organistation}}</li>
      <li class="list-group-item">Description: {{project.description}}</li>
      <li class="list-group-item">Created Date: {{project.created}}</li>  -->
    </ul>
  </div>
{% endblock content %}

PWC_DASHBOARD/templates/associates/associates_list.html
{% extends "layouts/base.html" %} {% block title %} Dashboard {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} 
{% block content %}
<div class="container">
<div class="page-header">
  <div class="page-block">
    <div class="row align-items-center">
      <div class="col-md-12">
        <div class="page-header-title">
          <h5 class="m-b-10">Associates List</h5>
        </div>
        <ul class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/"><i class="feather icon-home"></i></a>
          </li>
          
          <li class="breadcrumb-item">
            <a href="javascript:">Associates</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<hr>

<div class="card Recent-Users">
    <div class="card-header">
      <h5>All Associates</h5>
    </div>
    <div class="scroll">
      <div class="card-block px-0 py-3">
        <div class="table-responsive">
          <table class="table table-hover">
                <thead>
                  <tr>
                    <td>Created</td>
                    <td>Name</td>
                    
                    <td>Designation</td>
                    <td >Join Date</td>
                    <td>Projects</td>
                    <td >Technology</td>
                    <td style="color: rgb(216, 20, 20)">Action</td>
                  </tr>
                </thead>
            <tbody>
                {% for i in associate %}
              <tr class="unread">
                <td>
                   
                        <h6 class="text-muted">{{i.created|date:"M Y"}}
                        </h6>
                      </td>
                </td>
                <td>
                  <h6 class="mb-1"><a href="{% url 'associates-detail' i.id%}">{{i.name}}</a></h6>
                  <p class="m-0">{{i.email}}</p>
                </td>
                <td>{{i.designation}}</td>
                <td >{{i.joindate}}</td>
                <td >{{i.occupency}}</td>
                <td>{% for j in i.technology.all %}{{ j }}<br/>{% endfor %}
                </td>
                 
                <td>
                  <a
                    href="{% url 'associates-update' i.id %}"
                    class="label theme-bg2 text-white f-12"
                    >Update</a
                  >
                  <a
                  href="{% url 'associates-delete' i.id %}"
                  class="label theme-bg text-white f-12"
                  >Delete</a
                > 
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content%}
{% block javascripts %}{% endblock javascripts %}

PWC_DASHBOARD/templates/associates/associates_update.html
{% extends "layouts/base.html" %} {% block title %} Project Update {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  
<style>
   html, body {
   min-height: 100%;
   }
  
   h1 {
   position: absolute;
   margin: 0;
   font-size: 40px;
   color: #fff;
   z-index: 2;
line-height: 83px;
   }
   textarea {
   width: calc(100% - 12px);
   padding: 5px;
   }
   .testbox {
   display: flex;
   justify-content: center;
   align-items: center;
   height: inherit;
   padding: 20px;
   }
   form {
   width: 100%;
   padding: 20px;
   border-radius: 6px;
   background: #fff;
   box-shadow: 0 0 8px #3f4d67; 
   }
   .banner {
   position: relative;
   height: 300px;
   background-image: url("/uploads/media/default/0001/02/e2502bb5e1dab7d5cc9b011c745033821aad632c.jpeg");  
   background-size: cover;
   display: flex;
   justify-content: center;
   align-items: center;
   text-align: center;
   }
   .banner::after {
   content: "";
   background-color: rgba(0, 0, 0, 0.2); 
   position: absolute;
   width: 100%;
   height: 100%;
   }
   input, select, textarea {
   margin-bottom: 10px;
   border: 1px solid #ccc;
   border-radius: 3px;
   }
   input {
   width: calc(100% - 10px);
   padding: 5px;
   }
   input[type="date"] {
   padding: 4px 5px;
   }
  
   .item:hover p, .item:hover i, .question:hover p, .question label:hover, input:hover::placeholder {
   color:  #006622;
   }
   .item input:hover, .item select:hover, .item textarea:hover {
   border: 1px solid transparent;
   box-shadow: 0 0 3px 0  #006622;
   color: #006622;
   }
   .item {
   position: relative;
   margin: 10px 0;
   }
   .item span {
   color: red;
   }
   input[type="date"]::-webkit-inner-spin-button {
   display: none;
   }
   .item i, input[type="date"]::-webkit-calendar-picker-indicator {
   position: absolute;
   font-size: 20px;
   color: #00b33c;
   }
   .item i {
   right: 1%;
   top: 30px;
   z-index: 1;
   }
.week {
   display:flex;
   justify-content: space-between ;
  
   }
   .colums {
   display:flex;
   justify-content:space-between;
   flex-direction:row;
   flex-wrap:wrap;
   }
   .colums div {
   width:48%;
   }
   [type="date"]::-webkit-calendar-picker-indicator {
   right: 1%;
   z-index: 2;
   opacity: 0;
   cursor: pointer;
   }
   input[type=radio], input[type=checkbox]  {
   display: none;
   }
   label.radio {
   position: relative;
display: inline-block;
   margin: 5px 20px 15px 0;
   cursor: pointer;
   }
   .question span {
   margin-left: 30px;
   }
   .question-answer label {
   display: block;
   }
  
  
   .flax {
   display:flex;
   justify-content:space-around;
   }
   .btn-block {
   margin-top: 10px;
   text-align: center;
   }
  
  
   @media (min-width: 568px) {
   .name-item, .city-item {
   display: flex;
   flex-wrap: wrap;
   justify-content: space-between;
   }
   .name-item input, .name-item div {
   width: calc(50% - 20px);
   }
   .name-item div input {
   width:97%;}
   .name-item div label {
   display:block;
   padding-bottom:5px;
   }
   .container{
          margin-top: 60px;
      }
   }

  
   #id_type{
      border-color:#1de9b6;
      height: 30px;
      width: 100px;
  
   }
   #id_technology{
        height: 100px;
        width: 200px;
       
    
   }

   
 </style>
 {%endblock stylesheets%}
{% block content %}
 

   
     
<div class="container">
   <div class="page-header">
   <div class="page-block">
     <div class="row align-items-center">
       <div class="col-md-12">
         <div class="page-header-title">
           <h5 class="m-b-10"> Update Associates</h5>
         </div>
         <ul class="breadcrumb">
           <li class="breadcrumb-item">
             <a href="/"><i class="feather icon-home"></i></a>
           </li>
           
           <li class="breadcrumb-item">
             <a href="javascript:">  Associates </a>
           </li>
         </ul>
       </div>
     </div>
   </div>
 </div>
         
          <form method="POST">
            {% csrf_token%}
           <div class="colums">
          <div class="item">
            <label for="fname"> Name</label>
            {{form.name}}
          </div>
          <div class="item">
            <label for="email"> Email</label>
            {{form.email}}
          </div>
 <div class="item">
            <label for="designation">Designation</label>
            {{form.designation}}
          </div>
  <div class="item">
            <label for="date">Join date</label>
            {{form.joindate}}
          </div>
          <div class="item">
            <label for="date">Technology</label>
            <br>
            {{form.technology}}
          </div>
  
 
            
                     
                         
          </div>
                </fieldset>
        <div class="btn-block">
          <button class="btn btn-dark" type="submit" >Submit</button>
        </div>
      </form>
    </div>



   </div>

{% endblock content %}

PWC_DASHBOARD/templates/associates/delete.html
     {% extends "layouts/base-fullscreen.html" %}

     {% block title %} Associates Delete{% endblock %} 
     
     <!-- Specific CSS goes HERE -->
     {% block stylesheets %}{% endblock stylesheets %}
     
     {% block content %}
     <style>
     #id_email {
      width: 400px;
      height: 40px;
      border-color:#1de9b6;
   }
</style>
     <div class="auth-wrapper">
         <div class="auth-content">
             <div class="auth-bg">
                 <span class="r"></span>
                 <span class="r s"></span>
                 <span class="r s"></span>
                 <span class="r"></span>
             </div>
             <div class="card">
                 <div class="card-body text-center">
                     <div class="mb-4">
                         <i class="feather icon-mail auth-icon"></i>
                     </div>

                     <h5 class="mb-4">Do you want to delete the associate -
                      <br> <small style="color:red;">{{obj|capfirst}} </small>?</h5>
                     <form class="p-0" id="contact" method="POST">
                      {% csrf_token%}
                      {{form.as_p}}
                     <p class="mb-0 text-muted"><button class="label theme-bg text-white f-12">Delete</button></p>
                     </form>
                     <p class="mb-0 text-muted"><a class="label theme-bg2 text-white f-12" href="{{request.META.HTTP_REFERER}}">Cancle</a> </p>
                 </div>
             </div>
         </div>
     </div>
     
     {% endblock content %}
     
     <!-- Specific Page JS goes HERE  -->
     {% block javascripts %}{% endblock javascripts %}
     


  