PWC_DASHBOARD/PWC_DASHBOARD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/', include('project.urls')),
    path('manager/', include('manager.urls')),
    path('', include('dashboard.urls')),
]

PWC_DASHBOARD/manager/urls.py
from django import views
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.ManagerListView.as_view(), name="manager-list"),
    path('managercreate/', views.ManagerCreateView.as_view(), name="manager-create"),
    path('managerdetail/<str:pk>',
         views.Managerdetail, name="manager-detail"),

    #     path('managerdetail/<str:pk>',
    #          views.ManagerDetailView.as_view(), name="manager-detail"),
    #     path('managerupdate/<str:pk>',
    #          views.ManagerUpdateView.as_view(), name="manager-update"),
    path('managerdelete/<str:pk>',
         views.ManagerDeleteView.as_view(), name="manager-delete"),
    path('update_user/', views.Update_profile, name='update_user'),
]

PWC_DASHBOARD/project/models.py
from operator import mod
from pyexpat import model
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_manager = models.BooleanField(default=False)
    name = models.CharField(max_length=100, null=True)
    email = models.EmailField(unique=True)
    designation = models.CharField(max_length=150, null=True)
    username = models.CharField(max_length=100, null=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Manager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organistation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.email


class Status(models.Model):
    # imformation,test,dev,pwd,aws,.....
    name = models.CharField(max_length=50)
    # organistation=models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


def get_status():
    return Status.objects.get(name="Green")


TYPE_CHOICES = (
    ("Erp", "Erp"),
    ("aws", "aws"),
    ("Azure", "Azure"),
    ("salesforce", "salesforce"),
    ("5", "5"),
    ("6", "6"),
    ("7", "7"),
    ("8", "8"),
)


class Project(models.Model):

    title = models.CharField(max_length=200, null=False, blank=True)
    description = models.TextField(null=False, blank=True)
    client = models.CharField(max_length=50, null=False, blank=True)
    from_duration = models.DateField(null=True, blank=True)
    to_duration = models.DateField(null=True, blank=True)
    type = models.CharField(
        max_length=20,
        choices=TYPE_CHOICES,
        null=True
    )
    # phase = models.CharField(max_length=50, null=False, blank=True)
    # source=models.CharField(choices=SOURCE_CHOICE,max_length=100)
    organistation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    manager = models.ForeignKey(Manager, on_delete=models.CASCADE)
    status = models.ForeignKey(
        "Status", related_name="projects", on_delete=models.SET_NULL, null=True, blank=True, default=get_status)
    test = models.CharField(max_length=100, null=True,
                            blank=True, default="Green")
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)

    def __str__(self):
        return self.title
# employee


class Associates(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    manager = models.ForeignKey(Manager, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=False, blank=True)
    email = models.EmailField(null=True, blank=True)
    designation = models.CharField(max_length=100, null=False, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)

    def __str__(self):
        return self.name
# phase


class Phase(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Technology(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Associate(models.Model):

    name = models.CharField(max_length=200, null=False, blank=True)
    email = models.EmailField(null=True, blank=True)
    designation = models.CharField(max_length=100, null=False, blank=True)
    joindate = models.DateField(null=True)
    occupency = models.IntegerField(null=True, blank=True, default=0)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)
    technology = models.ManyToManyField(Technology)

    def __str__(self):
        return self.name


class Project_Associate(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    associate = models.ForeignKey(Associate, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)

    def __str__(self):
        return self.project.title + ":" + self.associate.name


class Technoproject(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    manager = models.ForeignKey(Manager, on_delete=models.CASCADE)
    associates = models.ForeignKey(Associates, on_delete=models.CASCADE)
    technology = models.ForeignKey(Technology, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)

    def __str__(self):
        return self.project.title + ":" + self.associates.name + ":" + self.technology.name


class PhaseDurationOfProject(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    phase = models.ForeignKey(Phase, on_delete=models.CASCADE)
    from_date = models.DateField(null=True, blank=True)
    to_date = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)
    # organistation=models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return (self.project.title)+" -- "+self.phase.name+" -- " + str(self.from_date)+" -- "+str(self.to_date)

PWC_DASHBOARD/templates/phase_duration/delete.html
     {% extends "layouts/base.html" %} {% block title %} Associates Delete {% endblock %}

     <!-- Specific CSS goes HERE -->
     {% block stylesheets %}{% endblock stylesheets %} 
     {% block content %}
       <style>
           .container{
               margin-top: 40px;
           }
       </style>
     
         <div class="main-content">
             <section class="iq-contactbox pt-0">
                <div class="container">
                  <div class="page-header">
                     <div class="page-block">
                       <div class="row align-items-center">
                         <div class="col-md-12">
                           <div class="page-header-title">
                             <h5 class="m-b-10">Delete Phase </h5>
                           </div>
                           <ul class="breadcrumb">
                             <li class="breadcrumb-item">
                               <a href="/"><i class="feather icon-home"></i></a>
                             </li>
                             
                             <li class="breadcrumb-item">
                               <a href="javascript:">Projects</a>
                             </li>
                           </ul>
                         </div>
                       </div>
                     </div>
                   </div>
                   <hr>
                   <!-- <div class="row justify-content-between"> -->
                      <div class="col-lg-12 align-self-center">
                         <div class="contact-box">
                            <h3>Do you want to delete the Associate- <small style="color:red;">{{obj|capfirst}} </small>?</h3>
                            <form class="p-0" id="contact" method="POST">
                             {% csrf_token%}
                             {{form.as_p}}
                               <div class="contact-form mt-4">
                                  <div class="row">
                                        
                                        
                                        <button  name="submit" type="submit" value="Submit" class="btn btn-danger" data-wow-duration="1.0s">Delete</button>
                                        <div>
                                      </div>
     </div> 
                                     </div> 
                                  </div>
                               </div>
                               
                            </form>
     <hr>
                            <a href="{{request.META.HTTP_REFERER}}"><button  name="cancle" type="cancle" value="cancle" class="btn btn-success" data-wow-duration="1.0s">Cancle</button></a> 
     
                         </div>
                      </div>
                   </div>
                </div>
             </section>
             <!--=================================
             Clients -->
             
             <!--=================================
             Clients -->
          </div>
          {% endblock content %}
     
     
          {% block javascripts %}{% endblock javascripts %}
     

PWC_DASHBOARD/templates/phase_duration/phase_duration_add.html
{% extends "layouts/base.html" %} {% block title %} Phase Data Add {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} 
{% block content %}
{% load static %}
  <style>
      .container{
          margin-top: 40px;
      }
      #id_phase {
         width: 200px;
         height: 40px;
         border-color:#1de9b6;
     }
     #id_from_date {
      width: 200px;
      height: 40px;
      border-color:#1de9b6;
  }
  #id_to_date {
   width: 200px;
   height: 40px;
   border-color:#1de9b6;
}
  </style>



    <div class="main-content">
        <section class="iq-contactbox pt-0">
           <div class="container">
            <div class="page-header">
               <div class="page-block">
                 <div class="row align-items-center">
                   <div class="col-md-12">
                     <div class="page-header-title">
                       <h5 class="m-b-10">Add Phase </h5>
                     </div>
                     <ul class="breadcrumb">
                       <li class="breadcrumb-item">
                         <a href="/"><i class="feather icon-home"></i></a>
                       </li>
                       
                       <li class="breadcrumb-item">
                         <a href="javascript:">Projects</a>
                       </li>
                     </ul>
                   </div>
                 </div>
               </div>
             </div>
             <hr>
              <!-- <div class="row justify-content-between"> -->
                 <div class="col-lg-12 align-self-center">
                    <div class="contact-box">
                       <h3>Add Project Phase and Duration</h3>
                       <form class="p-0" id="contact" method="POST">
                        {% csrf_token%}
                          <div class="contact-form mt-4">

                              <div class="row">
                                <div class="col-lg-4 col-sm-12 mb-3">
                                   <div class="form-group">
                                      <label class="mb-2"><b>Phase :</b>           </label>
                                      {{form.phase}}
                                   </div>
                                </div>
                                <div class="col-lg-4 col-sm-12 mb-3">
                                    <div class="form-group" Placeholder="Email" >
                                       <label class="mb-f"><b>Phase Start Date :</b></label>
                                       {{form.from_date}}
                                    </div>
                                 </div>
                                 <div class="col-lg-4 col-sm-12 mb-3">
                                    <div class="form-group" Placeholder="Email" >
                                       <label class="mb-f"><b>Phase End Date :</b></label>
                                       {{form.to_date}}
                                    </div>
                                 </div>
                                </div>

                                   <button  name="submit" type="submit" value="Submit" class="btn btn-dark" data-wow-duration="1.0s">Add</button>

                                </div> 
                             </div>
                             
                                
                             
                          </div>
                          
                       </form>
                    </div>
                    
                 </div>
              </div>
           </div>
        </section>
        
        <!--=================================
        Clients -->
        
        <!--=================================
        Clients -->
     </div>
     {% endblock content %}



        
  {% block js %}
  <script>

   document.getElementById('id_phase').classList.add('form-control')
   document.getElementById('id_status').classList.add('form-control')
   document.getElementById('id_description').rows = '5'

  </script>
  {% endblock js %}
  {% block javascripts %}{% endblock javascripts %}

PWC_DASHBOARD/templates/phase_duration/phase_duration_get.html
{% extends "layouts/base.html" %} {% block title %} Phase Data {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} 
{% block content %}
<style>
  .room-container {
    display: grid;
    /* grid-template-columns: 1fr 1fr; */
    margin-top: 60px;
   
  }
  

  </style>
  

 
  <div class="room-container">
   
  <div class="container">
    <div class="page-header">
      <div class="page-block">
        <div class="row align-items-center">
          <div class="col-md-12">
            <div class="page-header-title">
              <h5 class="m-b-10">Phase List</h5>
            </div>
            <ul class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="/"><i class="feather icon-home"></i></a>
              </li>
              
              <li class="breadcrumb-item">
                <a href="javascript:">Projects</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-lg-8 col-sm-12 mb-3">
        <h3>Phase & Duration </h3>
          </div>
      <div class="col-lg-4 col-sm-12 mb-3">
    {% if request.user.is_manager %}
    <a href="{% url 'add_phase_duration' project.id %}"
      ><button
        name="submit"
        type="submit"
        value="Submit"
        class="btn btn-outline-secondary"
        data-wow-duration="1.0s"
      >
      Add Project Phase
      </button></a
    >
   
    {%endif%}
      </div>
      
    </div>
    <table class="table table-striped table-responsive-stack" id="tableOne">
      <thead>
        <tr>
          <th>Phase</th>
          <th>Phase Start Date</th>
          <th>Phase End Date</th>
          <th style="color: rgb(216, 20, 20)">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for i in phase_duration %}
        <tr>
          <td >{{i.phase}}</th>
          <td >{{i.from_date}}</td>
          <td >{{i.to_date}}</td>
          
          <td >
            <a  class="label theme-bg2 text-white f-12" href="{%url 'update_phase_duration' i.id %}"
              >Update</a
            >|
            <a  class="label theme-bg text-white f-12" href="{% url 'delete_phase_duration' i.id%}"
              >Delete</a>
          </td>
        </tr>
        {% endfor%}
      </tbody>
    </table>
  </div>
</div>


{% endblock content %}


{% block js %}

<script>

  $(document).ready(function() {

   
    // inspired by http://jsfiddle.net/arunpjohny/564Lxosz/1/
    $('.table-responsive-stack').each(function (i) {
       var id = $(this).attr('id');
       //alert(id);
       $(this).find("th").each(function(i) {
          $('#'+id + ' td:nth-child(' + (i + 1) + ')').prepend('<span class="table-responsive-stack-thead">'+             $(this).text() + ':</span> ');
          $('.table-responsive-stack-thead').hide();
          
       });
       
 
       
    });
 
    
    
    
    
 $( '.table-responsive-stack' ).each(function() {
   var thCount = $(this).find("th").length; 
    var rowGrow = 100 / thCount + '%';
    //console.log(rowGrow);
    $(this).find("th, td").css('flex-basis', rowGrow);   
 });
    
    
    
    
 function flexTable(){
    if ($(window).width() < 768) {
       
    $(".table-responsive-stack").each(function (i) {
       $(this).find(".table-responsive-stack-thead").show();
       $(this).find('thead').hide();
    });
       
     
    // window is less than 768px   
    } else {
       
       
    $(".table-responsive-stack").each(function (i) {
       $(this).find(".table-responsive-stack-thead").hide();
       $(this).find('thead').show();
    });
       
       
 
    }
 // flextable   
 }      
  
 flexTable();
    
 window.onresize = function(event) {
     flexTable();
 };
    
    
    
    
 
   
 // document ready  
 });
 
 
 
 
</script>
{% endblock js %}

PWC_DASHBOARD/templates/phase_duration/phase_duration_update.html
{% extends "layouts/base.html" %} {% block title %} Phase Data Update {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} 
{% block content %}
{% load static %}
  <style>
      .container{
          margin-top: 40px;
      }
      #id_phase {
         width: 200px;
         height: 40px;
         border-color:#1de9b6;
     }
     #id_from_date {
      width: 200px;
      height: 40px;
      border-color:#1de9b6;
  }
  #id_to_date {
   width: 200px;
   height: 40px;
   border-color:#1de9b6;
}
  </style>



    <div class="main-content">
        <section class="iq-contactbox pt-0">
           <div class="container">
            <div class="page-header">
               <div class="page-block">
                 <div class="row align-items-center">
                   <div class="col-md-12">
                     <div class="page-header-title">
                       <h5 class="m-b-10">Phase Update</h5>
                     </div>
                     <ul class="breadcrumb">
                       <li class="breadcrumb-item">
                         <a href="/"><i class="feather icon-home"></i></a>
                       </li>
                       
                       <li class="breadcrumb-item">
                         <a href="javascript:">Projects</a>
                       </li>
                     </ul>
                   </div>
                 </div>
               </div>
             </div>
             <hr>
              <!-- <div class="row justify-content-between"> -->
                 <div class="col-lg-12 align-self-center">
                    <div class="contact-box">
                       <h3>Update Project Phase and Duration</h3>
                       <form class="p-0" id="contact" method="POST">
                        {% csrf_token%}
                          <div class="contact-form mt-4">

                              <div class="row">
                                <div class="col-lg-4 col-sm-12 mb-3">
                                   <div class="form-group">
                                      <label class="mb-2">Phase</label>
                                      {{form.phase}}
                                   </div>
                                </div>
                                <div class="col-lg-4 col-sm-12 mb-3">
                                    <div class="form-group" Placeholder="Email" >
                                       <label class="mb-f">Phase Start Date</label>
                                       {{form.from_date}}
                                    </div>
                                 </div>
                                 <div class="col-lg-4 col-sm-12 mb-3">
                                    <div class="form-group" Placeholder="Email" >
                                       <label class="mb-f">Phase End Date</label>
                                       {{form.to_date}}
                                    </div>
                                 </div>
                                </div>

                                   <button  name="submit" type="submit" value="Submit" class="btn btn-outline-success" data-wow-duration="1.0s">Update</button>

                                </div> 
                             </div>
                             
                                
                             
                          </div>
                          
                       </form>
                    </div>
                    
                 </div>
              </div>
           </div>
        </section>
        
        <!--=================================
        Clients -->
        
        <!--=================================
        Clients -->
     </div>
     {% endblock content %}



        
  {% block js %}
  <script>

   document.getElementById('id_phase').classList.add('form-control')
   document.getElementById('id_status').classList.add('form-control')
   document.getElementById('id_description').rows = '5'

  </script>
  {% endblock js %}
  {% block javascripts %}{% endblock javascripts %}