PWC_DASHBOARD/PWC_DASHBOARD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/', include('project.urls')),
    path('manager/', include('manager.urls')),
    path('', include('dashboard.urls')),
]

PWC_DASHBOARD/manager/urls.py
from django import views
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.ManagerListView.as_view(), name="manager-list"),
    path('managercreate/', views.ManagerCreateView.as_view(), name="manager-create"),
    path('managerdetail/<str:pk>',
         views.Managerdetail, name="manager-detail"),

    #     path('managerdetail/<str:pk>',
    #          views.ManagerDetailView.as_view(), name="manager-detail"),
    #     path('managerupdate/<str:pk>',
    #          views.ManagerUpdateView.as_view(), name="manager-update"),
    path('managerdelete/<str:pk>',
         views.ManagerDeleteView.as_view(), name="manager-delete"),
    path('update_user/', views.Update_profile, name='update_user'),
]

PWC_DASHBOARD/manager/models.py
from django.db import models

# Create your models here.

PWC_DASHBOARD/project/models.py
from operator import mod
from pyexpat import model
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_manager = models.BooleanField(default=False)
    name = models.CharField(max_length=100, null=True)
    email = models.EmailField(unique=True)
    designation = models.CharField(max_length=150, null=True)
    username = models.CharField(max_length=100, null=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Manager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organistation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.email


class Status(models.Model):
    # imformation,test,dev,pwd,aws,.....
    name = models.CharField(max_length=50)
    # organistation=models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


def get_status():
    return Status.objects.get(name="Green")


TYPE_CHOICES = (
    ("Erp", "Erp"),
    ("aws", "aws"),
    ("Azure", "Azure"),
    ("salesforce", "salesforce"),
    ("5", "5"),
    ("6", "6"),
    ("7", "7"),
    ("8", "8"),
)


class Project(models.Model):

    title = models.CharField(max_length=200, null=False, blank=True)
    description = models.TextField(null=False, blank=True)
    client = models.CharField(max_length=50, null=False, blank=True)
    from_duration = models.DateField(null=True, blank=True)
    to_duration = models.DateField(null=True, blank=True)
    type = models.CharField(
        max_length=20,
        choices=TYPE_CHOICES,
        null=True
    )
    # phase = models.CharField(max_length=50, null=False, blank=True)
    # source=models.CharField(choices=SOURCE_CHOICE,max_length=100)
    organistation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    manager = models.ForeignKey(Manager, on_delete=models.CASCADE)
    status = models.ForeignKey(
        "Status", related_name="projects", on_delete=models.SET_NULL, null=True, blank=True, default=get_status)
    test = models.CharField(max_length=100, null=True,
                            blank=True, default="Green")
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)

    def __str__(self):
        return self.title
# employee


class Associates(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    manager = models.ForeignKey(Manager, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=False, blank=True)
    email = models.EmailField(null=True, blank=True)
    designation = models.CharField(max_length=100, null=False, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)

    def __str__(self):
        return self.name
# phase


class Phase(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Technology(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Associate(models.Model):

    name = models.CharField(max_length=200, null=False, blank=True)
    email = models.EmailField(null=True, blank=True)
    designation = models.CharField(max_length=100, null=False, blank=True)
    joindate = models.DateField(null=True)
    occupency = models.IntegerField(null=True, blank=True, default=0)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)
    technology = models.ManyToManyField(Technology)

    def __str__(self):
        return self.name


class Project_Associate(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    associate = models.ForeignKey(Associate, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)

    def __str__(self):
        return self.project.title + ":" + self.associate.name


class Technoproject(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    manager = models.ForeignKey(Manager, on_delete=models.CASCADE)
    associates = models.ForeignKey(Associates, on_delete=models.CASCADE)
    technology = models.ForeignKey(Technology, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)

    def __str__(self):
        return self.project.title + ":" + self.associates.name + ":" + self.technology.name


class PhaseDurationOfProject(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    phase = models.ForeignKey(Phase, on_delete=models.CASCADE)
    from_date = models.DateField(null=True, blank=True)
    to_date = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)
    # organistation=models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return (self.project.title)+" -- "+self.phase.name+" -- " + str(self.from_date)+" -- "+str(self.to_date)

PWC_DASHBOARD/manager/forms.py
from django.forms.models import ModelForm
from django.contrib.auth import get_user_model
from django import forms
User = get_user_model()


class ManagerForm(ModelForm):
    
    class Meta:
        model = User
        fields = ('email',)
        labels = {
            'email': '',
        }
    
        widgets = {
            'email': forms.EmailInput(attrs={'placeholder': 'Enter Email Address Of Manager'})
        }


class Updateuser(ModelForm):
    class Meta:
        model = User
        fields = ['name', 'username',  'designation']

PWC_DASHBOARD/manager/views.py
from urllib import request
from django.shortcuts import redirect, render, reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from project.models import *
from .forms import*
from .mixin import OrganiserAndLoginRequiredMixin
from django.core.mail import send_mail
from django.core.mail import EmailMessage
import random
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required(login_url='login')
def Update_profile(request):
    user = request.user
    form = Updateuser(instance=user)
    if request.method == 'POST':
        form = Updateuser(request.POST, request.FILES, instance=user)

        if form.is_valid():
            print(form.data)
            form.save()
            return redirect('manager-list')
    context = {
        'form': form
    }
    return render(request, 'update-user.html', context)


@login_required(login_url='login')
def Managerdetail(request, pk):
    user = request.user
    manager = Manager.objects.get(id=pk)
    c = str(user) == str(manager)

    context = {'manager': manager, "c": c

               }
    return render(request, 'managerdetail.html', context)


class ManagerListView(OrganiserAndLoginRequiredMixin, generic.ListView):
    template_name = "managerlist.html"

    def get_queryset(self):
        if self.request.user.is_organisor:
            # print(self.request.user.id)
            return Manager.objects.filter(organistation=self.request.user.userprofile)
        else:
            my_p = Manager.objects.get(user=self.request.user)
            organistation = my_p.organistation
            # print(organistation)
            # (organistation=organistation)
            return Manager.objects.filter(organistation=organistation)


class ManagerCreateView(OrganiserAndLoginRequiredMixin, generic.CreateView):
    template_name = "managercreate.html"
    form_class = ManagerForm

    def get_success_url(self):
        return reverse("manager-list")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_manager = True
        user.is_organisor = False
        user.set_password(f"{random.randint(0, 1000000)}")
        user.save()
        Manager.objects.create(
            user=user, organistation=self.request.user.userprofile)
        html_content = f'''
            <div style="font-family: Helvetica,Arial,sans-serif;min-width:1000px;overflow:auto;line-height:2">
                <div style="margin:50px auto;width:80%;padding:20px 0">
                    <div style="border-bottom:1px solid #eee">
                    <a href="" style="font-size:1.4em;color: #46c894;text-decoration:none;font-weight:600">PWC</a>
                    </div>
                    <p style="font-size:1.1em">Hi,.</p>
                    <p>You have been added as a manager  with user id {user.email} . </p>
<p><a href="http://127.0.0.1:8000/reset-password/">Click here to reset your password.</a></p>
                    <p>Use your email-  and reset your password.</p>

                    <p style="font-size:0.9em;">Thank You</p>
                    <hr style="border:none;border-top:1.5px solid #eee" />
                </div>
            </div>
            '''
        mail = EmailMessage(
            'PwC',
            html_content,
            None,
            [user.email],

        )
        mail.content_subtype = "html"
        mail.send()

        # send_mail(
        #     subject="you are invited to be an agent",
        #     message="You were added as an agent on CRM plese login to start working .Your login credintial are username="+user.username+" and password="+user.password,
        #     from_email="admin@admin.com",
        #     recipient_list=['user.email']
        # )

        # agent.organistation=self.request.user.userprofile
        # agent.save()
        return super(ManagerCreateView, self).form_valid(form)


# class ManagerDetailView(OrganiserAndLoginRequiredMixin, generic.DetailView):
#     template_name = "managerdetail.html"

#     def get_queryset(self):

#         m = Manager.objects.all()

#         return m


# class ManagerUpdateView(OrganiserAndLoginRequiredMixin, generic.UpdateView):
#     template_name = "managerupdate.html"
#     form_class = ManagerForm

#     def get_success_url(self):
#         return reverse('manager-list')

#     def get_queryset(self):
#         organistation = self.request.user.userprofile
#         return Manager.objects.filter(organistation=organistation)


class ManagerDeleteView(OrganiserAndLoginRequiredMixin, generic.DeleteView):
    template_name = "manager_confirm_delete.html"
    a = 0

    def get_queryset(self):
        if self.request.user.is_organisor:
            organistation = self.request.user.userprofile
            return Manager.objects.filter(organistation=organistation)
        else:
            self.a = 1
            manager = self.request.user

            return Manager.objects.filter(user=manager)

    def get_success_url(self):
        if self.a == 1:
            return reverse("logout")
        else:
            return reverse("manager-list")

PWC_DASHBOARD/manager/templates/manager_confirm_delete.html
       


     {% extends "layouts/base-fullscreen.html" %}

     {% block title %} Manager Delete{% endblock %} 
     
     <!-- Specific CSS goes HERE -->
     {% block stylesheets %}{% endblock stylesheets %}
     
     {% block content %}
  

     <div class="auth-wrapper">
         <div class="auth-content">
             <div class="auth-bg">
                 <span class="r"></span>
                 <span class="r s"></span>
                 <span class="r s"></span>
                 <span class="r"></span>
             </div>
             <div class="card">
                 <div class="card-body text-center">
                     <div class="mb-4">
                         <i class="feather icon-mail auth-icon"></i>
                     </div>

                     <h5 class="mb-4">Do you want to delete the Manager - <br> <small style="color:red;">{{manager.user.username}} </small>?</h5>
                     <form class="p-0" id="contact" method="POST">
                      {% csrf_token%}
                      {{form.as_p}}
                     <p class="mb-0 text-muted"><button class="label theme-bg text-white f-12">Delete</button></p>
                     </form>
                     <p class="mb-0 text-muted"><a class="label theme-bg2 text-white f-12" href="{{request.META.HTTP_REFERER}}">Cancle</a> </p>
                 </div>
             </div>
         </div>
     </div>
     
     {% endblock content %}
     
     <!-- Specific Page JS goes HERE  -->
     {% block javascripts %}{% endblock javascripts %}
     

PWC_DASHBOARD/manager/templates/managercreate.html
{% extends "layouts/base.html" %} {% block title %} Associates Update {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} 
{% block content %}
{% load static %}
  <style>
      .container{
          margin-top: 50px;
      }
      #id_email {
         width: 350px;
         height: 40px;
         border-color:#1de9b6;

     }
  </style>



           <div class="container">
            <div class="page-header">
               <div class="page-block">
                 <div class="row align-items-center">
                   <div class="col-md-12">
                     <div class="page-header-title">
                       <h5 class="m-b-10"> Add / Create Manager</h5>
                     </div>
                     <ul class="breadcrumb">
                       <li class="breadcrumb-item">
                         <a href="/"><i class="feather icon-home"></i></a>
                       </li>
                       
                       <li class="breadcrumb-item">
                         <a href="javascript:">Manager</a>
                       </li>
                     </ul>
                   </div>
                 </div>
               </div>
             </div>
             <hr>
              <!-- <div class="row justify-content-between"> -->
                 <div class="col-lg-12 align-self-center">
                    <div class="contact-box">
                       <h4>Create a new Manager</h4>
                       <form class="p-0" id="contact" method="POST">
                        {% csrf_token%}
                          <div class="contact-form mt-4">
                            
                                
                                <div class="col-lg-6 col-sm-12 mb-3">
                                    <div class="form-group" Placeholder="Email" >
                                       
                                       
                                       {{form.email}}
                                    </div>
                                 </div>
                                
                                   
                                   
                                   <button  name="submit" type="submit" value="Submit" class="btn btn-success" data-wow-duration="1.0s">Create</button>

                                </div> 
                             </div>
                          </div>
                          
                       </form>
                    </div>
                    
                 </div>
              </div>
           </div>
        </section>
        
        <!--=================================
        Clients -->
        
        <!--=================================
        Clients -->
     </div>
     {% endblock content %}

        
     {% block javascripts %}{% endblock javascripts %}

PWC_DASHBOARD/manager/templates/managerdetail.html
{% extends "layouts/base.html" %} {% block title %} Manager Detail{% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} {% block content %}

<style>
  .container {
    margin-top: 60px;
  }
</style>
<div class="container">
  <div class="page-header">
    <div class="page-block">
      <div class="row align-items-center">
        <div class="col-md-12">
          <div class="page-header-title">
            <h5 class="m-b-10">Manager Details</h5>
          </div>
          <ul class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="/"><i class="feather icon-home"></i></a>
            </li>
            
            <li class="breadcrumb-item">
              <a href="javascript:">Manager</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <ul class="list-group">
    <li
      class="list-group-item active"
      style="border-color: #4fc98d; background-color: #3f4d67"
    >
      This is the detail of <b>{{manager.user.username}}</b>
    </li>
    <li class="list-group-item">Name: {{manager.user.name}}</li>
    <li class="list-group-item">Email: {{manager.user.email}}</li>
    <li class="list-group-item">Created: {{manager.created}}</li>
    <li class="list-group-item">Organization: {{manager.organistation}}</li>
  </ul>

  <div style="margin-top: 12px">
    {% if c %}

    <a href="{% url 'update_user'%}"
      ><button
        type="button"
        class="btn btn-success"
       
      >
        Update
      </button></a
    >
   
    <a href="{% url 'manager-delete' manager.id %}"
      ><button
        type="button"
        class="btn btn-danger"
        
      >
        Delete
      </button></a
    >
  </div>
</div>
{% endif %} {%endblock%}
{% block javascripts %}{% endblock javascripts %}

PWC_DASHBOARD/manager/templates/managerlist.html
{% extends "layouts/base.html" %} {% block title %} Manager List {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}  {% block content %}
<style>
  .container {
    margin-top: 50px;
  }
</style>

<div class="container">
  <div class="page-header">
    <div class="page-block">
      <div class="row align-items-center">
        <div class="col-md-12">
          <div class="page-header-title">
            <h5 class="m-b-10">Manager List</h5>
          </div>
          <ul class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="/"><i class="feather icon-home"></i></a>
            </li>
            
            <li class="breadcrumb-item">
              <a href="javascript:">Manager</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <hr />

  <div>
    <!-- <h3>Existing Managers</h3> -->

    <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">User Name</th>
          <th scope="col">Email</th>
        </tr>
      </thead>
      <tbody>
        {% for i in object_list %}
        <tr>{% if i.user.name %}
          <td>{{i.user.name}}</td>
          {%else%}
          <td><small style="color: red;"> *update your profile</small></td>
          {% endif %}
          <td>{% if i.user.name %}
            <a href="{% url 'manager-detail' i.id%}">{{i.user.username}}</a>
            {%else%}
            <a href="{% url 'manager-detail' i.id%}"><small style="color: red;">*Update</small></a>
            {% endif %}
          </td>

          <td>{{i.user.email}}</td>
        </tr>
        {% endfor%}
      </tbody>
    </table>
  </div>
  {% endblock content %}
</div>
{% block javascripts %}{% endblock javascripts %}

PWC_DASHBOARD/manager/templates/managerupdate.html
{% extends "layouts/base.html" %} {% block title %} Update Manager {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} 
{% block content %}
  <style>
      .container{
          margin-top: 160px;
      }
  </style>



    <div class="main-content">
        <section class="iq-contactbox pt-0">
           <div class="container">
              <!-- <div class="row justify-content-between"> -->
                 <div class="col-lg-12 align-self-center">
                    <div class="contact-box">
                       <h3>Update the detail of manager- {{manager.user}}</h3>
                       <form class="p-0" id="contact" method="POST">
                        {% csrf_token%}
                        <div class="contact-form mt-4">
                             <div class="row">
                                <div class="col-lg-6 col-sm-12 mb-3">
                                    <div class="form-group">
                                       <label class="mb-2">Username</label>
                                       {{form.username}}
                                    </div>
                                 </div>
                                <div class="col-lg-6 col-sm-12 mb-3">
                                    <div class="form-group">
                                       <label class="mb-2">Email</label>
                                       {{form.email}}
                                    </div>
                                 </div>
                                <div class="col-lg-6 col-sm-12 mb-3">
                                   <div class="form-group">
                                      <label class="mb-2">Name</label>
                                      {{form.name}}
                                   </div>
                                </div>
                                <div class="col-lg-6 col-sm-12 mb-3">
                                    <div class="form-group">
                                       <label class="mb-2">Designation</label>
                                       {{form.designation}}
                                    </div>
                                 </div>

                                   <button  name="submit" type="submit" value="Submit" class="button pull-right wow fadeInUp" data-wow-duration="1.0s">Update</button>

                                </div> 
                             </div>
                          </div>
                          
                       </form>
                    </div>
                 </div>
              </div>
           </div>
        </section>
        <!--=================================
        Clients -->
        
        <!--=================================
        Clients -->
     </div>

   
          {% endblock content %}

          {% block javascripts %}{% endblock javascripts %}

PWC_DASHBOARD/manager/templates/update-user.html
{% extends "layouts/base.html" %} {% block title %} Update Manager {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} 
{% block content %}
  <style>
      .container{
          margin-top: 60px;
      }
      #id_username {
         width: 250px;
         height: 40px;
         border-color:#1de9b6;
     }
     #id_name {
      width: 250px;
      height: 40px;
      border-color:#1de9b6;
  }
  #id_designation {
   width: 250px;
   height: 40px;
   border-color:#1de9b6;
}
  </style>



    <div class="main-content">
        <section class="iq-contactbox pt-0">
           <div class="container">
            <div class="page-header">
               <div class="page-block">
                 <div class="row align-items-center">
                   <div class="col-md-12">
                     <div class="page-header-title">
                       <h5 class="m-b-10">Update Manager </h5>
                     </div>
                     <ul class="breadcrumb">
                       <li class="breadcrumb-item">
                         <a href="/"><i class="feather icon-home"></i></a>
                       </li>
                       
                       <li class="breadcrumb-item">
                         <a href="javascript:">Manager</a>
                       </li>
                     </ul>
                   </div>
                 </div>
               </div>
             </div>
             <hr>
              <!-- <div class="row justify-content-between"> -->
                 <div class="col-lg-12 align-self-center">
                    <div class="contact-box">
                       <h4>Update the detail of manager- <small style="color:#ff1818;"> {{user.email}}</small></h4>
                       <form class="p-0" id="contact" method="POST">
                        {% csrf_token%}
                        <div class="contact-form mt-4">
                             {% comment %} <div class="row"> {% endcomment %}
                                <div class="col-lg-6 col-sm-12 mb-3">
                                    <div class="form-group">
                                      <label for="username">User Name</label>
                                      <br>
                                       {{form.username}}
                                    </div>
                                 </div>
                                <div class="col-lg-6 col-sm-12 mb-3">
                                     <div class="form-group">
                                       <label for="name"> Full Name</label>
                                       <br>
                                       {{form.name}}
                                    </div> 
                                 </div>
                              
                                <div class="col-lg-6 col-sm-12 mb-3">
                                    <div class="form-group">
                                       <label for="designation">Designation</label>
                                       <br>
                                       {{form.designation}}
                                    </div>
                                 </div>

                                   <button  name="submit" type="submit" value="Submit" class="btn btn-dark" data-wow-duration="1.0s">Update</button>

                                </div> 
                             </div>
                          </div>
                          
                       </form>
                    </div>
                 </div>
              </div>
           </div>
        </section>
        <!--=================================
        Clients -->
        
        <!--=================================
        Clients -->
     </div>

   
          {% endblock content %}
          {% block javascripts %}{% endblock javascripts %}